In [1]:
from modules.util import *

folder_files = '/home/vassilis/bigdrive/vassilis/DNA_data'
folder_results = '/home/vassilis/bigdrive/vassilis/DNA_data/dezipped'

extract_gz(folder_files, folder_results)

Extracted duck to duck.fa
Extracted leopard to leopard.fa
Extracted leishan-spiny-toad to leishan-spiny-toad.fa
Extracted emu to emu.fa
Extracted common-wall-lizard to common-wall-lizard.fa
Extracted beluga to beluga.fa
Extracted chicken to chicken.fa
Error processing dezipped: [Errno 21] Is a directory: '/home/vassilis/bigdrive/vassilis/DNA_data/dezipped'
Extracted clown-anemonefish to clown-anemonefish.fa
Extracted two-toed-sloth to two-toed-sloth.fa
Extracted guppy to guppy.fa
Extracted blue-whale to blue-whale.fa
Extracted goodes-thornscrub-tortoise to goodes-thornscrub-tortoise.fa
Extracted human to human.fa
Extracted clawed-frog to clawed-frog.fa
Extracted golden-eagle to golden-eagle.fa
Extracted indian-cobra to indian-cobra.fa
Extracted chimpanzee to chimpanzee.fa
Extracted narwhal to narwhal.fa
Extracted komodo-dragon to komodo-dragon.fa
Extracted large-yellow-croaker to large-yellow-croaker.fa


In [1]:
from modules.tok_utils import lower_text, k_div_text

k_div_text('dataloc/guppy.fa.preprocessed_lower.txt',6)


11862284it [00:11, 1003387.65it/s]

Total misbehaved lines :  2322
So, 0.019574645152653572% of misbehaved lines


In [2]:
from modules.tok_utils import make_h5
from modules.tokenizer import SimpleTokenizer

yo=SimpleTokenizer(tok_dict_loc='new_toki_char/ordered_dna_char_R.pt')

make_h5('tokendata/char_ordered_dna_R.h5',tokenizer=yo,data_name='char_ordered_dna_R',destination_folder='h5chardna')

Got : tok_dict {'$': 0, 'a': 1, 'c': 2, 'g': 3, 't': 4, 'n': 5, '\n': 6}
Got : tok_dict_rev {0: '$', 1: 'a', 2: 'c', 3: 'g', 4: 't', 5: 'n', 6: '\n'}
Created empty dataset
Tensor shape: torch.Size([38134400240])
snippet ggtcgagctctggttttccggaactcgtat


100%|██████████| 38134400240/38134400240 [11:37<00:00, 54685480.42it/s]


In [24]:
from modules.dataset import TokenTextBOS
from modules.tokenizer import SimpleTokenizer

yo=SimpleTokenizer(tok_dict_loc='tokenizers/DNA_tok.pt')
yo2 = SimpleTokenizer(tok_dict_loc='test_toki/DNA_tok.pt')
a = TokenTextBOS('/rcp/csft_scratch/vassilis/DNA_perp/all_animals.h5',attn_length=256)
ar = TokenTextBOS('/rcp/csft_scratch/vassilis/DNA_perp/all_animals.h5',attn_length=256,backwards=True)
b = TokenTextBOS('/rcp/csft_scratch/vassilis/DNA_perp/all_animals_R.h5',attn_length=256,backwards=False)
br = TokenTextBOS('/rcp/csft_scratch/vassilis/DNA_perp/all_animals_R.h5',attn_length=256,backwards=True)



Got : tok_dict {'$': 0, 'A': 1, 'C': 2, 'G': 3, 'T': 4}
Got : tok_dict_rev {0: '$', 1: 'A', 2: 'C', 3: 'G', 4: 'T'}
Dataset contains 36467.81M tokens, resulting in 287148k examples.
Dataset contains 36467.81M tokens, resulting in 287148k examples.
Dataset contains 36467.81M tokens, resulting in 287148k examples.
Dataset contains 36467.81M tokens, resulting in 287148k examples.


In [25]:
print(yo.detokenize(a[0][0]))
print(yo.detokenize(ar[0][0]))

$AAGTTACAAAATATGCAGTAACAAACACAGTACAGATTATTCTTAAGCTAAAAACAGTTTGAAGGAACATTCTTCAGAAAGCTATGTATTTGTATTGCTTGAGAAACAGCTTTAGAAAAATATACAGAATTGTTACAGTTGCTACACACAAACATTAACATTTCCAACTAGGGACTCGAGCAGAAGTTGCTATGTCTCTCCTGCTTCACATTGTTTCCTGGCCAAGATTTCCTCTCATCCAGTTTAGCTTGTGCT
$TTCGTGTTCGATTTGACCTACTCTCCTTTAGAACCGGTCCTTTGTTACACTTCGTCCTCTCTGTATCGTTGAAGACGAGCTCAGGGATCAACCTTTACAATTACAAACACACATCGTTGACATTGTTAAGACATATAAAAAGATTTCGACAAAGAGTTCGTTATGTTTATGTATCGAAAGACTTCTTACAAGGAAGTTTGACAAAAATCGAATTCTTATTAGACATGACACAAACAATGACGTATAAAACATTGA


In [39]:
print(yo.detokenize(b[1][0]))
print(yo.detokenize(a[-4][0]))

$AATAGGAATAGGAGTTAAGTCTACATATCGTCCTTTGACAGACCCACAATAAGTGACCTTCTCCTACTAATGTGCACTTATACGATCAAGAACGGGTAGAGATTCGAGTTGTGACGAAAAGATCTTCTCGGTCGAGATGGTCGACCTTGTATGGTCTCTGGAGTCCTTCGGATCTCCAAGGTAATTGAAGATACTAACCCGGTAAAAGGAAACGAAAGTCTCAGCTGTCTTAAGACTTGGAGTTTTCCTTCACTA
$CTTCCTTTCATAGAGCTGGTTTGAAATACTCTTTTTGTAATATTTGGAAGTGGACATTGGCAGCGCTTTGAAGCCTATGTTGAAAATGGAAATATCTTCTCCTAAAAACCAGACAGAAGCATTCTCAGAAACTTCCTTGTGATGTGTGTACTCAAGTAACAGAGTTGAACCTTACTTTTGACAGAGCCGTTTTGAAACAGTCTTTTTGTAGAATCTGGAAGTAGATATTTGGATACCTTTGAGGATTTCTTTGGA


In [34]:
len(br)

287148136

In [2]:
from modules.dataset import TokenTextBOS
from modules.tokenizer import SimpleTokenizer

yor=SimpleTokenizer(tok_dict_loc='new_toki_char/ordered_dna_char_R.pt')
yo = SimpleTokenizer(tok_dict_loc='new_toki_char/ordered_dna_char.pt')
a = TokenTextBOS('h5chardna/char_ordered_dna.h5',attn_length=61+61)
ar = TokenTextBOS('h5chardna/char_ordered_dna_R.h5',attn_length=61*2,backwards=True)

Got : tok_dict {'$': 0, 'a': 1, 'c': 2, 'g': 3, 't': 4, 'n': 5, '\n': 6}
Got : tok_dict_rev {0: '$', 1: 'a', 2: 'c', 3: 'g', 4: 't', 5: 'n', 6: '\n'}
Got : tok_dict {'$': 0, 'a': 1, 'c': 2, 'g': 3, 't': 4, 'n': 5, '\n': 6}
Got : tok_dict_rev {0: '$', 1: 'a', 2: 'c', 3: 'g', 4: 't', 5: 'n', 6: '\n'}
Dataset contains 38134.40M tokens, resulting in 635573k examples.
Dataset contains 38134.40M tokens, resulting in 635573k examples.


In [53]:
print(yo.detokenize(a[-40][0]))
print('##')
print(yo.detokenize(a[0][1]))
print(yo.detokenize(ar[0][0]))
print('##')
print(yo.detokenize(ar[0][1]))

$tgatcccaaggcggttcctacatggaacttccaagaggc
tctttgccatggtggtgttggaaagctgcagttccctgaagacggtccagggaggcccag
gtgcacaccaacacggcaag
##
agaaagaggaggggaggtggaggaggaagaggaggaaaaagaggaagaggaagaggagga
agaggaagaggaagaggaagaggaagaggaagagaaggaacagaaggaggaagaagagga

$gcatgttttcaaagagaatg
gcagcatcttcccaaccctgaatattcctaaggaagcacgatcctcagcagaggaaaaga
ggcttcccatcctatgctcaaggccttttggtctcgagctg
##
gcatgttttcaaagagaatg
gcagcatcttcccaaccctgaatattcctaaggaagcacgatcctcagcagaggaaaaga
ggcttcccatcctatgctcaaggccttttggtctcgagctgg


In [4]:
len(a)

635573336

In [6]:
a.text_tensor.shape

(38134400228,)

In [5]:
a.text_tensor[(635573336-1)*61:635573336+63]

array([4, 3, 2, 1, 3, 2, 4, 3, 4, 2, 1, 1, 3, 1, 1, 1, 4, 4, 2, 2, 1, 4,
       3, 1, 3, 4, 6, 1, 4, 4, 4, 1, 4, 1, 4, 3, 3, 3, 1, 3, 1, 1, 2, 1,
       4, 4, 4, 1, 2, 2, 1, 4, 4, 3, 4, 2, 1, 2, 1, 3, 1, 4, 2, 1],
      dtype=uint8)

In [31]:
len('ggcttcccatcctatgctcaaggccttttggtctcgagctg')

41

In [ ]:
import h5py

# Open your HDF5 file
with h5py.File('h5chardna/char_ordered_dna.h5', 'r+') as file:
    # Read the dataset
    dset = file['tokens'][:]
    # Slice the dataset to exclude the last 40 entries
    sliced_dset = dset[:-40]
    
    # Delete the original dataset from the file
    del file['your_dataset_name']
    # Save the sliced dataset back to the file
    file.create_dataset('your_dataset_name', data=sliced_dset)

# Sixer tokenizer tests

In [5]:
from modules.dataset import TokenTextBOS
from modules.tokenizer import SixerTokenizer

toki = SixerTokenizer()
data = TokenTextBOS('dataloc/h5data/guppysixer.h5.h5',attn_length=10)

print(data[0][0])
print(toki.detokenize(data[0][0]))
print(toki.detokenize(data[0][1]))

Initializing Tokenizer
Generated 6-mer dictionary, length :  15627
Dataset contains 11.00M tokens, resulting in 2749k examples.
tensor([  0, 255, 255, 255, 255, 255, 255, 255, 255, 255])
$aagaataagaataagaataagaataagaataagaataagaataagaataagaat
aagaataagaataagaataagaataagaataagaataagaataagaataagaataagaat


In [1]:
import torch
saved_tends = torch.load('prep_utils/tokendata/all_6div/Data1.pt')

In [ ]:
from modules.tok_utils import make_h5
from modules.tokenizer import SixerTokenizer

toki = SixerTokenizer()

make_h5('tokendata/all_6div/',tokenizer=toki,data_name='all_6div',destination_folder='int16ver',dtype='int16')

In [76]:
from modules.dataset import TokenTextBOS
from modules.tokenizer import SixerTokenizer
import random

toki = SixerTokenizer()
data = TokenTextBOS('/rcp/csft_scratch/vassilis/DNA_perp/human_six.h5',attn_length=310)
i = random.randint(0,len(data))
print(data[i][0])
print('QUESTION : ')
print(toki.detokenize(data[i][0]))
print('ANSWER : ')
print(toki.detokenize(data[i][1]))

Initializing Tokenizer
Generated 6-mer dictionary, length :  15627


ValueError: File/Folder dataloc/h5data/human_six.h5 not found

# Test attention vs flash attention

In [1]:
from modules.models.mingpt.MinGPT import CausalSelfAttention,SlowCausalSelfAttention, compare_forwards, compare_speed
import torch

torch.manual_seed(0)
tester = CausalSelfAttention(embed_dim=10,n_heads=5,attn_length=5,dropout=0.)
tester2 = SlowCausalSelfAttention(embed_dim=10,n_heads=5,attn_length=5,dropout=0.)
# Show parameter number : 
print(sum(p.numel() for p in tester.parameters()))
print(sum(p.numel() for p in tester2.parameters()))

440
440


In [3]:
compare_speed(device='cuda',embed_dim=256,n_heads=8,attn_length=256,batch_size=128)

Slow attention : 1000 batches of size 128 took 12.92 seconds
Fast attention : 1000 batches of size 128 took 10.72 seconds


In [10]:
test_vec = torch.ones((3,5,10),dtype=torch.float32)
test_vec[:,3]=0
tester(test_vec)

tensor([[[-0.2272,  0.2708,  0.1933,  0.0689, -0.1342,  0.2754, -0.1823,
           0.0209,  0.0543,  0.2861],
         [-0.2272,  0.2708,  0.1933,  0.0689, -0.1342,  0.2754, -0.1823,
           0.0209,  0.0543,  0.2861],
         [-0.2272,  0.2708,  0.1933,  0.0689, -0.1342,  0.2754, -0.1823,
           0.0209,  0.0543,  0.2861],
         [-0.1704,  0.2031,  0.1450,  0.0516, -0.1007,  0.2065, -0.1367,
           0.0156,  0.0407,  0.2146],
         [-0.1703,  0.2269,  0.1584,  0.0454, -0.1002,  0.2149, -0.1540,
           0.0192,  0.0440,  0.2310]],

        [[-0.2272,  0.2708,  0.1933,  0.0689, -0.1342,  0.2754, -0.1823,
           0.0209,  0.0543,  0.2861],
         [-0.2272,  0.2708,  0.1933,  0.0689, -0.1342,  0.2754, -0.1823,
           0.0209,  0.0543,  0.2861],
         [-0.2272,  0.2708,  0.1933,  0.0689, -0.1342,  0.2754, -0.1823,
           0.0209,  0.0543,  0.2861],
         [-0.1704,  0.2031,  0.1450,  0.0516, -0.1007,  0.2065, -0.1367,
           0.0156,  0.0407,  0.2146],

In [11]:
tester.compare_forwards(test_vec)

Passed !
